### ISSUE TITLE
再ビルド時にtree3-thickが足りないとビルドが失敗する

### ISSUE THREAD

**Issue by yabuki** [spinute/ods#61]
新しい修正をmergeして、uplatexでbuildしようとしたら、表題のようなエラーメッセージをもらったが、jaでないlatexのほうのimagesから、tree3-thick*とcc-by*をコピーしたら、ビルドが完走したので、Makefileにコピーするエントリーを書くなどの措置がいるような気がします。

もちろん私が間違って図をコピーしているかもしれないので、確認を兼ねてissueを書いておきます。

**Comment by spinute** [comment]
お知らせいただきましてありがとうございます！

Wikiにビルド手順書を掲載しました。このうち、<https://github.com/spinute/ods/wiki/日本語版pdfの作成手順#コンパイルに欠如しているファイルの調整>にご指摘いただいたファイルのコピーに関する記述があります。

自分ではなかなか環境構築からやり直す機会がなく、また自分でビルドする人も多くないようなので、手順書の整備が後回しになっていました...。
お知らせいただきましてありがとうございました🙇

**Comment by spinute** [comment]
READMEにも、ビルド手順書へのリンクを記載しました。

**Comment by yabuki** [comment]
対応ありがとうございました。

**Comment by yabuki** [comment]
ちょうど過去のissueにあった手順を探してました。
